// src/components/ScougiUploader.tsx
'use client';
import { useEffect, useMemo, useState } from "react";
import AutoComplete from "./AutoComplete"
import { TrimOptions, TrimesterNames } from "@/enums/trimesterNames";
import { FileUp, Send } from 'lucide-react';
import DropboxChooser from "./DropboxChooser";
import { PDFDocument } from "pdf-lib";
import { downloadFromDropbox, splitDocToPages, uploadPage } from "@/lib/pdf";
import { revalidatePath } from "next/cache";

export const ScougiUploader = (props: { years: Record<string, number[]> }) => {
  const [yearValue, setYearValue] = useState("")
  const [trimValue, setTrimValue] = useState("")
  const [selectedFile, setSelectedFile] = useState<Dropbox.file | null>(null);
  const [processing, setProcessing] = useState(false);

  const trimOptions = useMemo(() =>
    TrimOptions.filter((_, i) => props.years?.[yearValue ?? '2022-2023']?.includes(i) ?? true)
  , [yearValue, props.years]);

  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    if (processing) return;
    setProcessing(true);

    // TODO :add proper toast notifications with sonner
    if (!selectedFile) {
      return;
    }
    if (trimValue === "") {
      return
    }

    try {
      let doc: PDFDocument;
      try {
        doc = await downloadFromDropbox(selectedFile.link)
      } catch (e) {
        console.error(e)
        return;
      }
      const pages = await splitDocToPages(doc);

      const res = await fetch(`/scougi/${yearValue}/${trimValue}/create`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          pages: pages.length,
        }),
      });
      if (!res.ok) {
        // TODO: Show with toast
        const resp = await res.json();
        console.error(resp.message);
        return;
      }

      const failedPages: number[] = [];
      for (let i = 0; i < pages.length; i++) {
        const ok = await uploadPage(yearValue, Number(trimValue), i, pages[i]);
        if (!ok) {
          failedPages.push(i);
        }
      }
      console.log(failedPages);
      revalidatePath('/admin')
    } catch (e) {
      console.error(e);
    } finally {
      setProcessing(false);
    }
  };

  return (
    <form onSubmit={handleSubmit} className="flex flex-wrap gap-4 items-end">
      <AutoComplete name="year" label="Jaar" items={Object.keys(props.years)} value={yearValue} onChange={setYearValue} />
      <label className="form-control w-full max-w-xs">
        <div className="label">
          <span className="label-text">Trimester</span>
        </div>
        <select value={trimValue} onChange={e => setTrimValue(e.currentTarget.value)} className="select select-bordered">
          <option value="" disabled>Pick one</option>
          {trimOptions.map(o => (
            <option key={o.value} value={o.value}>{o.label}</option>
          ))}
        </select>
      </label>
      <div>
        {selectedFile && <div className="label"><span className="label-text">{selectedFile.name}</span></div>}
        <DropboxChooser
          appKey={"24ejhxqih5zow8j"}
          onSuccess={(files: Dropbox.file[]) => setSelectedFile(files[0])}
        >
          <div className="btn btn-primary">
            <FileUp />
            <span className="ml-2">Select scougi</span>
          </div>
        </DropboxChooser>
      </div>
      <button disabled={processing} type="submit" className={`btn btn-success ${processing ? "btn-disabled" : ""}`}>
        <Send />
        <span>Upload</span>
      </button>
    </form >
  )
}

// src/lib/components/ScougiUploader.svelte
<script lang="ts">
	import { TrimOptions } from '$lib/enums/trimesterNames';
	import Svelecte from 'svelecte';
	import DropboxChooser from './DropboxChooser.svelte';
	import Fa from 'svelte-fa';
	import { faFileUpload, faPaperPlane } from '@fortawesome/free-solid-svg-icons';
	import type { DropboxFile } from '$lib/types';
	import { toast } from 'svelte-sonner';
	import type { PDFDocument } from 'pdf-lib';
	import { downloadFromDropbox, splitDocToPages, uploadPage } from '$lib/pdf';
	import { trpc } from '$lib/trpc';
	import { writable } from 'svelte/store';
	import PageUploadProgress from './PageUploadProgress.svelte';

	export let years: Record<string, number[]>;

	const yearCreateFilter = (input: string) => {
		return input.match('d{4}-d{4}')?.length === 1;
	};

	let year: string;
	let trim: string;
	let file: DropboxFile;
	let processing = false;
	let uploadProgress = writable(0);

	$: newScougiMutation = trpc.scougi.create.mutation();
	$: newScougiPageMutation = trpc.scougi.addPage.mutation();

	const uploadScougi = async () => {
		if (processing) return;
		processing = true;

		// TODO :add proper toast notifications with sonner
		if (!file) {
			toast.error('No file selected');
			return;
		}
		if (year === '') {
			toast.error('No year selected');
			return;
		}
		if (trim === '') {
			toast.error('No trimester selected');
			return;
		}

		let toastResolver: () => void = () => {};
		toast.promise(
			new Promise<void>((res) => {
				toastResolver = res;
			}),
			{
				loading: PageUploadProgress,
				componentProps: {
					counter: uploadProgress
				},
				success: () => {
					return 'The scougi has been uploaded successfully!';
				},
				error: 'Error... :( Try again! Delete the scougi entry if visible in the table'
			}
		);

		try {
			let doc: PDFDocument;
			try {
				doc = await downloadFromDropbox(file.link);
			} catch (e) {
				console.error(e);
				toast.error('Failed to download scougi from dropbox');
				return;
			}
			const pages = await splitDocToPages(doc);

			$newScougiMutation.mutate({
				year,
				trim: Number(trim),
				pages: pages.length
			});
			if ($newScougiMutation.isError) {
				console.error($newScougiMutation.error.message);
				toast.error('Failed to create scougi', {
					description: $newScougiMutation.error.message
				});
				return;
			}

			const failedPages: number[] = [];
			for (let i = 0; i < pages.length; i++) {
				const pdfStr = uploadPage(pages[i]);
				if (pdfStr == '') {
					throw new Error('Failed to extract page from pdf');
				}
				try {
					$newScougiPageMutation.mutate({
						data: pdfStr,
						year,
						trim: Number(trim),
						page: i
					});
				} catch (e) {
					console.error(e);
					failedPages.push(i);
				}
				uploadProgress.set(i + 1);
			}
			toastResolver();
			console.log(failedPages);
		} catch (e) {
			console.error(e);
			toast.error('Failed to upload scougi');
		} finally {
			processing = false;
		}
	};

	$: trimOptions = TrimOptions.filter((_, i) => years?.[year ?? '2022-2023']?.includes(i) ?? true);
</script>

<form class="flex flex-wrap gap-4 items-end">
	<label class="form-control max-w-xs w-full">
		<div class="label">
			<span class="label-text">Jaar</span>
		</div>
		<Svelecte
			placeholder=""
			name="year"
			options={Object.keys(years)}
			bind:value={year}
			creatable
			createFilter={yearCreateFilter}
		/>
	</label>
	<label class="form-control w-full max-w-xs">
		<div class="label">
			<span class="label-text">Trimester</span>
		</div>
		<select bind:value={trim} class="select select-bordered">
			<option value="" disabled>Pick one</option>
			{#each trimOptions as option}
				<option value={option.value}>{option.label}</option>
			{/each}
		</select>
	</label>
	<div>
		{#if file}
			<div class="label"><span class="label-text">{file.name}</span></div>
		{/if}
		<DropboxChooser bind:file>
			<div class="btn btn-primary">
				<Fa icon={faFileUpload} size={'lg'} />
				<span class="ml-2">Select scougi</span>
			</div>
		</DropboxChooser>
	</div>
	<button class="btn btn-success" on:click={uploadScougi}>
		<Fa icon={faPaperPlane} size={'lg'} />
		Upload
	</button>
</form>
